exports.data = [
  {
    name: '翱翔•飞越地平线',
    ename: 'attSoaringOverHorizon',
    lands: 'adventure-isle',
    desc:
      '沿着山坡，攀上探险岛上神秘的亚柏栎天文台。在远古的部落魔法的作用下，您将踏上一段激动人心的环球之旅，从空中欣赏地球上最美的景致。 ',
    pic: ['shdr-att-soaring-hero-new.jpg'],
    fastpass: 1,
    icon: 'shdr-att-soaring-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '4D;刺激;风光;室内',
    duration: 0,
    tips: null,
    lng: '121.6717021420',
    lat: '31.1498546788'
  },
  {
    name: '创极速光轮',
    ename: 'attTronLightcyclePowerRun',
    lands: 'tomorrowland',
    desc: '进入“创”的电子网络世界，随着极速光轮、极速转向，全力奔驰吧！',
    pic: ['shdr-att-tron-lightcycle-power-run-hero-new.jpg'],
    fastpass: 1,
    icon: 'shdr-att-tron-lightcycle-power-run-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '刺激;快速;灯光',
    duration: 0,
    tips: null,
    lng: '121.6632298924',
    lat: '31.1480863461'
  },
  {
    name: '雷鸣山漂流',
    ename: 'attRoaringRapids',
    lands: 'adventure-isle',
    desc:
      '登上漂筏探险之旅，遭遇意想不到的转折。深入黑暗的深渊，和凶猛的巨兽赛跑，在激流中辗转翻腾，一定要坚持到底！',
    pic: ['shdr-att-roaring-rapids-hero-new-again.jpg'],
    fastpass: 1,
    icon: 'shdr-att-roaring-rapids-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '刺激;快速;水花四溅',
    duration: 0,
    tips: null,
    lng: '121.6697262027',
    lat: '31.1492387682'
  },
  {
    name: '七个小矮人矿山车',
    ename: 'attSevenDwarfsMineTrain',
    lands: 'fantasyland',
    desc: '适合全家体验的过山车—穿梭在《白雪公主和七个小矮人》的钻石矿山中。',
    pic: ['shdr-att-seven-dwarfs-mine-train-hero-new.jpg'],
    fastpass: 1,
    icon: 'shdr-att-seven-dwarfs-mine-train-hero-sq-new.jpg',
    is_host: 1,
    type: 0,
    tag: '刺激;快速',
    duration: 0,
    tips: null,
    lng: '121.6661695937',
    lat: '31.1511992306'
  },
  {
    name: '幻想曲旋转木马',
    ename: 'attFantasiaCarousel',
    lands: 'gardens-imagination',
    desc:
      '乘坐飞马，伴随迪士尼《幻想曲》中恢弘大气的交响乐，回旋在梦幻的世界里。',
    pic: ['shdr-att-fantasia-carousel-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-fantasia-carousel-hero-sq-new-again2.jpg',
    is_host: 1,
    type: 0,
    tag: '缓速;室外',
    duration: 0,
    tips: null,
    lng: '121.6677950125',
    lat: '31.1488668726'
  },
  {
    name: '小飞侠天空奇遇',
    ename: 'attPeterPansFlight',
    lands: 'fantasyland',
    desc:
      '和小飞侠、奇妙仙子还有梦幻岛的同伴一起遨游天际，朝着右边第二颗星的方向前行。',
    pic: ['shdr-att-peter-pans-flight-hero-new.jpg'],
    fastpass: 1,
    icon: 'shdr-att-peter-pans-flight-hero-sq-new-again2.jpg',
    is_host: 1,
    type: 0,
    tag: '缓速;室内;动画',
    duration: 0,
    tips: null,
    lng: '121.6643456914',
    lat: '31.1498402259'
  },
  {
    name: '巴斯光年星际营救',
    ename: 'attBuzzLightyearPlanetRescue',
    lands: 'tomorrowland',
    desc:
      '投身战斗，竭尽全力消灭索克天王手下骇人的机器人部队，拯救外星人的星球！',
    pic: ['shdr-att-buzz-lightyear-planet-rescue-hero-new.jpg'],
    fastpass: 1,
    icon: 'shdr-att-buzz-lightyear-planet-rescue-hero-sq-new-again2.jpg',
    is_host: 1,
    type: 0,
    tag: '射击;室内',
    duration: 0,
    tips: null,
    lng: '121.6640613773',
    lat: '31.1476318014'
  },
  {
    name: '加勒比海盗：沉落宝藏之战',
    ename: 'attPiratesOfCaribbean',
    lands: 'treasure-cove',
    desc:
      '伙计们，来加入杰克船长的海盗队伍，向海洋进发，来一场寻宝之旅，沿途还会遇上怪兽呢！',
    pic: ['shdr-att-pirates-of-caribbean-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-pirates-of-caribbean-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '全息;室内;黑暗',
    duration: 0,
    tips: null,
    lng: '121.6682671760',
    lat: '31.1518021131'
  },
  {
    name: '探险家独木舟',
    ename: 'attExplorerCanoes',
    lands: 'treasure-cove',
    desc:
      '登上独木舟，划着船桨，探索“宝藏湾”主题园区的海盗领地和“探险岛”主题园区的雾林神秘水域。',
    pic: ['shdr-att-explorer-canoes-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-explorer-canoes-hero-sq-new-again2.jpg',
    is_host: 1,
    type: 0,
    tag: '水花四溅;室外',
    duration: 0,
    tips: null,
    lng: '121.6686694126',
    lat: '31.1501065188'
  },
  {
    name: '漫游童话时光',
    ename: 'attOnceUponTimeAdventure',
    lands: 'fantasyland',
    desc:
      '穿过魔镜，进入全新的世界，沉浸在奇幻魔法中，切身感受白雪公主的童话世界。在奇幻童话城堡中，以前所未有的方式体验这位迪士尼公主的故事。',
    pic: ['shdr-att-once-upon-time-adventure-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-once-upon-time-adventure-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '动画片;公主;室内',
    duration: 0,
    tips: null,
    lng: '121.6661374070',
    lat: '31.1498677733'
  },
  {
    name: '喷气背包飞行器',
    ename: 'attJetPacks',
    lands: 'tomorrowland',
    desc: '加速，再加速，带着这次未来之旅令人激动的兴奋感出发！',
    pic: ['shdr-att-jet-packs-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-jet-packs-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '旋转;室外',
    duration: 0,
    tips: null,
    lng: '121.6651074387',
    lat: '31.1477833165'
  },
  {
    name: '小飞象',
    ename: 'attDumboFlyingElephant',
    lands: 'gardens-imagination',
    desc: '乘着小飞象在空中尽情飞翔！他是奇想花园冉冉升起的超级明星。',
    pic: ['shdr-att-dumbo-flying-elephant-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-dumbo-flying-elephant-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '旋转;室外',
    duration: 0,
    tips: null,
    lng: '121.6663519837',
    lat: '31.1488393247'
  },
  {
    name: '小熊维尼历险记',
    ename: 'attAdventuresWinniePooh',
    lands: 'fantasyland',
    desc: '进入百亩森林，探索小熊维尼和朋友们的美妙世界！',
    pic: ['shdr-att-the-many-adventures-of-winnie-the-pooh-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-the-many-adventures-of-winnie-the-pooh-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '室内;动画',
    duration: 0,
    tips: null,
    lng: '121.6652738306',
    lat: '31.1518526159'
  },
  {
    name: '晶彩奇航',
    ename: 'attVoyageToCrystalGrotto',
    lands: 'fantasyland',
    desc:
      '借助想象的翅膀，晶彩奇航将迪士尼经典故事栩栩如生地呈现在游客眼前，游客仿佛置身于一场视听盛宴中。',
    pic: ['shdr-att-voyage-to-the-crystal-grotto-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-voyage-to-the-crystal-grotto-hero-sq-new.jpg',
    is_host: 1,
    type: 0,
    tag: '缓速;室外',
    duration: 0,
    tips: null,
    lng: '121.6650162436',
    lat: '31.1499550074'
  },
  {
    name: '古迹探索营',
    ename: 'attChallengeTrails',
    lands: 'adventure-isle',
    desc:
      '三条让人兴奋不已的上升绳索道横穿过雷鸣山，带领探险者们通过河谷、瀑布和峭壁，从宜人的山川景致一路到达令人叹为观止的山洞景观，帮助探险家破解最神秘古老的遗迹。',
    pic: ['shdr-att-camp-discovery-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-camp-discovery-hero-sq-new-again.jpg',
    is_host: 1,
    type: 0,
    tag: '室外',
    duration: 0,
    tips: null,
    lng: '121.6703806617',
    lat: '31.1498861384'
  },
  {
    name: '旋转疯蜜罐',
    ename: 'attHunnyPotSpin',
    lands: 'fantasyland',
    desc:
      '与同伴一起乘坐旋转疯蜜罐，在自由控制的旋转中体验寻找美味的乐趣。小熊维尼和他的伙伴在等着你！',
    pic: ['shdr-att-honey-pot-spin-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-honey-pot-spin-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '缓速;室内',
    duration: 0,
    tips: null,
    lng: '121.6652110000',
    lat: '31.1514860000'
  },
  {
    name: '船奇戏水滩',
    ename: 'attShipwreckShore',
    lands: 'treasure-cove',
    desc: '在“宝藏湾”主题园区的一艘海盗船残骸中探索戏水，感受互动乐趣。',
    pic: ['shdr-att-shipwreck-shore-hero-new-again.jpg'],
    fastpass: 0,
    icon: 'shdr-att-shipwreck-shore-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室外',
    duration: 0,
    tips: null,
    lng: '121.6682295304',
    lat: '31.1510431296'
  },
  {
    name: '探秘海妖复仇号',
    ename: 'attSirensRevenge',
    lands: 'treasure-cove',
    desc: '登上真正的海盗船，体验海盗的刺激生活与惊险行动。',
    pic: ['shdr-att-sirens-revenge-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-sirens-revenge-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室外',
    duration: 0,
    tips: null,
    lng: '121.6689108114',
    lat: '31.1512497337'
  },
  {
    name: '爱丽丝梦游仙境迷宫',
    ename: 'attAliceWonderlandMaze',
    lands: 'fantasyland',
    desc: '穿越爱丽丝梦游仙境中蜿蜒的迷宫，参加愉快的疯狂茶会派对。',
    pic: ['alice-hero-test.jpg'],
    fastpass: 0,
    icon: 'shdr-att-alice-wonderland-maze-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室外;迷宫',
    duration: 0,
    tips: null,
    lng: '121.6659872033',
    lat: '31.1507952041'
  },
  {
    name: '奇幻童话城堡里的迪士尼公主们',
    ename: 'attDisneyPrincessesStorybookCourt',
    lands: 'fantasyland',
    desc:
      '世界上最高、最大、最具互动性的迪士尼城堡，汇聚了所有迪士尼公主。它是上海迪士尼乐园中耀眼的标志性建筑。',
    pic: [
      'shdr-char-characters-disney-princesses-storybook-court-hero-new.jpg'
    ],
    fastpass: 0,
    icon: 'shdr-char-characters-disney-princesses-storybook-court-hero-sq-new.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室外',
    duration: 0,
    tips: null,
    lng: '121.6661266783',
    lat: '31.1498815471'
  },
  {
    name: '创界：雪佛兰数字挑战',
    ename: 'attTronRealm',
    lands: 'tomorrowland',
    desc:
      '探索奇妙的未来驾驶世界，游客们在这里能体验全新一代雪佛兰概念车与创世界尖端技术的融合。',
    pic: ['shdr-att-tron-realm-chevrolet-digital-challenge-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-tron-realm-chevrolet-digital-challenge-hero-sq-new.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;科技;室内',
    duration: 0,
    tips: null,
    lng: '121.6632750000',
    lat: '31.1480440000'
  },
  {
    name: '太空幸会史迪奇',
    ename: 'attStitchEncounter',
    lands: 'tomorrowland',
    desc: '快来近距离接触莉萝的顽皮小伙伴史迪奇，他正在银河欢快地遨游！',
    pic: ['shdr-att-stitch-encounter-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-stitch-encounter-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室内',
    duration: 0,
    tips: null,
    lng: '121.6648610000',
    lat: '31.1473490000'
  },
  {
    name: '星球大战远征基地',
    ename: 'attStarWarsLaunchBay',
    lands: 'tomorrowland',
    desc:
      '尽情沉醉于《星球大战》故事之中，甚至还可一睹《星球大战：原力觉醒》中角色人物的风采！',
    pic: ['shdr-att-star-wars-launch-bay-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-star-wars-launch-bay-hero-sq-new.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室内',
    duration: 0,
    tips: null,
    lng: '121.6633049943',
    lat: '31.1468879961'
  },
  {
    name: '漫威英雄总部',
    ename: 'attMarvelUniverse',
    lands: 'gardens-imagination',
    desc: '深入漫威英雄总部，您将有幸遇到一些自己喜爱的漫威超级英雄！',
    pic: ['shdr-att-marvel-universe-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-att-marvel-universe-hero-sq-new-again.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室内',
    duration: 0,
    tips: null,
    lng: '121.6653381088',
    lat: '31.1487107678'
  },
  {
    name: '奇想花园的米奇俱乐部',
    ename: 'attMeetMickeyGardensImagination',
    lands: 'gardens-imagination',
    desc:
      '在参观完引人入胜的展览之后，做好准备——和闻名世界的米奇进行一场面对面的近距离接触吧！',
    pic: ['shdr-char-characters-mickey-mouse-gardens-imagination-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-char-characters-mickey-mouse-gardens-imagination-hero-sq-new.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室内',
    duration: 0,
    tips: null,
    lng: null,
    lat: null
  },
  {
    name: '欢笑聚友会的丛林迪士尼朋友们',
    ename: 'attJungleFriendsHappyCircle',
    lands: 'adventure-isle',
    desc:
      '环绕在这座丛林之岛周围的是地球上最广、最深、最蓝的一片海洋——来这里邂逅几位深受喜爱的迪士尼朋友吧！',
    pic: ['shdr-char-characters-jungle-friends-adventure-isle-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-char-characters-jungle-friends-adventure-isle-hero-sq-new.jpg',
    is_host: 0,
    type: 0,
    tag: '互动项目;室内',
    duration: 0,
    tips: null,
    lng: null,
    lat: null
  },
  {
    name: '点亮奇梦：夜光幻影秀',
    ename: 'entIgniteDreamNighttimeSpectacular',
    lands: 'gardens-imagination',
    desc:
      '施展迪士尼魔力，用令人惊叹的特效点亮夜幕，看“奇幻童话城堡”如何华丽变身！',
    pic: ['shdr-ent-ignite-dream-nighttime-spectacular-hero-new-again.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-ignite-dream-nighttime-spectacular-hero-sq-new-again.jpg',
    is_host: 1,
    type: 5,
    tag: '烟火;惊艳;裸眼3D;室外娱乐',
    duration: 20,
    tips: '最佳观赏点：奇想花园，建议提前20分钟寻找位置',
    lng: null,
    lat: null
  },
  {
    name: '风暴来临:杰克船长之惊天特技大冒险',
    ename: 'entEyeOfStormCaptainJacksSpectacular',
    lands: 'treasure-cove',
    desc:
      '对杰克船长的追捕正在进行中，充满大场面特技，同时也让您捧腹大笑，结局更是惊心动魄。来亲眼见证这场演出精彩！',
    pic: ['shdr-ent-eye-of-storm-captain-jacks-spectacular-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-eye-of-storm-captain-jacks-spectacular-hero-sq-new.jpg',
    is_host: 0,
    type: 4,
    tag: '舞台表演;惊险;室内娱乐',
    duration: 30,
    tips: '宝藏湾，开场前5分钟关闭入口',
    lng: null,
    lat: null
  },
  {
    name: '冰雪奇缘：欢唱盛会',
    ename: 'entFrozenSingAlongCelebration',
    lands: 'fantasyland',
    desc:
      '加入互动表演，与安娜、艾莎和克里斯托夫一起欢唱，亲身体验音乐与魔法的神奇魅力。',
    pic: ['shdr-ent-frozen-sing-along-celebration-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-frozen-sing-along-celebration-hero-sq-new.jpg',
    is_host: 0,
    type: 4,
    tag: '舞台表演;歌舞剧;室内娱乐',
    duration: 18,
    tips: '梦幻世界-林间剧场，开场前5分钟关闭入口',
    lng: null,
    lat: null
  },
  {
    name: '大白超酷活力秀',
    ename: 'entBaymaxSuperExerciseExpo',
    lands: 'tomorrowland',
    desc:
      '欢迎来到大白超酷活力秀！和《超能陆战队》里人见人爱的医护机器人大白一起锻炼身体。白天，大白会在明日世界的E空间•百事舞台等着大家来学习他的绝招“芥末无疆斩”和“神行弓步”。 ',
    pic: ['shdr-ent-baymax-super-exercise-expo-hero.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-baymax-super-exercise-expo-hero-sq.jpg',
    is_host: 0,
    type: 5,
    tag: '运动;室外娱乐',
    duration: 30,
    tips: '明日世界，室外演出',
    lng: null,
    lat: null
  },
  {
    name: '明日世界E空间聚乐部',
    ename: 'entClubDestinE',
    lands: 'tomorrowland',
    desc:
      '每当夜幕降临，在此上演的互动趣味音乐剧充满活力，融合先进科技，让您领略明日世界的精髓。',
    pic: ['shdr-ent-club-destin-e-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-club-destin-e-hero-sq-new-again.jpg',
    is_host: 0,
    type: 5,
    tag: '运动;室外娱乐',
    duration: 200,
    tips: '明日世界，室外演出',
    lng: null,
    lat: null
  },
  {
    name: '金色童话盛典',
    ename: 'entGoldenFairytaleFanfare',
    lands: 'gardens-imagination',
    desc:
      '快加入在“奇幻童话城堡”上演的华丽盛典，和广受喜爱的迪士尼公主们一起唱颂属于她们的故事和歌曲。',
    pic: ['shdr-ent-golden-fairytale-fanfare-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-golden-fairytale-fanfare-hero-sq-new-again.jpg',
    is_host: 0,
    type: 5,
    tag: '舞台表演;室外娱乐',
    duration: 17,
    tips: '奇想花园，室外演出',
    lng: null,
    lat: null
  },
  {
    name: '米奇童话专列',
    ename: 'entMickeysStorybookExpress',
    lands: 'gardens-imagination',
    desc: '由米奇领衔的火车主题巡游满载幻想、趣味和音乐，快加入我们吧！',
    pic: ['shdr-ent-mickeys-storybook-express-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-mickeys-storybook-express-hero-sq-new.jpg',
    is_host: 1,
    type: 5,
    tag: '巡游;室外娱乐',
    duration: 40,
    tips: '环迪士尼大道巡游',
    lng: null,
    lat: null
  },
  {
    name: '人猿泰山：丛林的呼唤',
    ename: 'entTarzanCallOfJungle',
    lands: 'adventure-isle',
    desc:
      '屏息凝神欣赏一场不可思议的现场舞台演出，聆听美妙的音乐，欣赏或诙谐幽默或温馨浪漫的剧情，观赏酷炫的高空特技表演。',
    pic: ['shdr-ent-tarzan-call-of-jungle-hero-new.jpg'],
    fastpass: 0,
    icon: 'shdr-ent-tarzan-call-of-jungle-hero-sq-new.jpg',
    is_host: 0,
    type: 4,
    tag: '舞台表演;杂技;室内娱乐',
    duration: 30,
    tips: '探险岛-故事舞台，开场前5分钟关闭入口',
    lng: null,
    lat: null
  }
]
